#!/bin/env bash

export RESET_FORMATTING="0"
export BOLD_TEXT="1"
export CYAN_TEXT="36"

exec 7> >( perl -e '$|=1; while(sysread STDIN,$LINE,9999)
                          {
                            printf "\x1b[%sm\x1b[%sm%s\x1b[%sm", $ENV{BOLD_TEXT},
                                                                 $ENV{CYAN_TEXT},
                                                                 $LINE,
                                                                 $ENV{RESET_FORMATTING}
                          }'
          )

function stderr_redirect(){ exec 2>&7;} 
trap "stderr_redirect;" DEBUG

echo "Command that does not error will be the default teminal color"
echo "Example executing command ls -alF --color=auto"
ls -alF --color=auto

echo ""
echo "Showing a command that prints to stderr"
echo "This will be trapped, then redirected to format the text to bold cyan."
ls --alF --color-auto

echo ""